version: 0.0
os: linux

files:
  - source: ./dist
    destination: /opt/process/dist

  - source: ./package.json
    destination: /opt/process

  - source: ./deployment
    destination: /opt/process/deployment

  - source: ./node_modules
    destination: /opt/process/node_modules

permissions:
  - object: /opt/process
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: deployment/codedeploy/before-install.sh
      runas: ec2-user
      timeout: 300

  ApplicationStart:
    - location: deployment/codedeploy/application-start.sh
      runas: ec2-user
      timeout: 300
